### ISSUE TITLE
Rules are missing the information about turn offset in the direction ordering

### ISSUE THREAD

**Issue by herbertnon** [JohnnyGuye/code-of-kutulu#1]
In the rules there's an indication about the order of directions used (UP, RIGHT, DOWN, LEFT) when choosing between two paths of the same length, but this replay (https://www.codingame.com/replay/317467036) exhibit a ``turn`` offset that is not mentioned anywhere.

I believe it corresponds to this line in the referee: https://github.com/JohnnyGuye/code-of-kutulu/blob/c19529dd3fb8ed3faf004225eb9bacda0b27dfc3/codeOfKutulu/src/main/java/codeofkutulu/models/Minion.java#L93

**Comment by eulerscheZahl** [comment]
Statement is updated for multiplayer game.
