### ISSUE TITLE
Pathfinder algorithm is subtly flawed

### ISSUE THREAD

**Issue by jpeg729** [JohnnyGuye/code-of-kutulu#2]
I expected `pathitem.totalPrevisionalLength` for each path to be equal to the cumulative length traversed + the manhattan distance between the current cell and the final target cell.

But actually, `pathitem.totalPrevisionalLength` is equal to the cumulative length traversed + 1.

The problem on line [102 of AStar.java](https://github.com/JohnnyGuye/code-of-kutulu/blob/master/codeOfKutulu/src/main/java/codeofkutulu/pathfinder/AStar.java#L102) is that `toCell` is not the final target, but the next cell to visit, i.e. distance 1 from `fromCell`.

**Comment by jpeg729** [comment]
I think if you correct it then in some circumstances it may run slightly faster, and it may stop respecting the order of directional preference in the game statement.

**Comment by eulerscheZahl** [comment]
We discussed it during the contest.
The A* is actually a BFS, but it finds shortest paths. Because of the direction priorities we won't change it.
